name: Living For Real
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6181702050380409
title: Living For Real
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f98514'
    - '#d50737'
    - '#9cbc11'
    - '#0896d4'
  brandStrength: 0.4997666394338012
  lightness: 0.768206141423434
  saturation: 0.8508427487686276
  rhythmicContrast: 0.6776508970651776
purpose: []
